# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NeuNn_FkjudrSAzNEDu_PrhqjCBUVl4m
"""


from openai import OpenAI

client = OpenAI(
    api_key = "REMOVED"
)

def get_completion(prompt, model="gpt-3.5-turbo"):
    messages = [
        {"role": "user", "content": prompt}
    ]

    Response = client.chat.completions.create(
        model=model,
        messages=messages,
        temperature=0,
    )

    return Response.choices[0].message.content

text = f"""
سيكون من الأفضل أن تعبر عن ما تريد أن يفعله النموذج من خلال
تقديم تعليمات واضحة ومحددة. كما يمكنك جعله
يؤدي هذا إلى توجيه النموذج نحو المخرجات المطلوبة
وقبوله ثم الحصول على مخرجات عالية ذات صلة. كنبات
أو ردوة جيب مما يؤكد أن النموذج يمكن كتاب
مطلبية وأضمة من كتابة مطلبية قصيرة.
في العديد من الحالات: توفر الطلبات الأطول تبرز من الوضع
وسائل النموذج، مما قد يؤدي إلى
مخرجات أكثر تفصيلا وذات صلة.
"""

prompt =  f"""
لخص النص المحدد بعلامات خلفية ثلاتية في جملة واحدة  \
{text}
"""

response = get_completion(prompt)
print(response)

prompt =  f"""
لخص النص المحدد بعلامات خلفية ثلاتية في جملة واحدة  \
'''{text}'''
"""

response = get_completion(prompt)
print(response)

prompt = f"""
قم بإنشاء قائمة بثلاثة عناوين كتب مكونة من \
مع مؤلفيها وأنواعها.

قم بتزويدها بتنسيق JSON بالمفاتيح التالية:
book_id, title, author, genre.
"""
response = get_completion(prompt)
print(response)

import json

# JSON string
response = """ {"books":
[
    {
        "book_id": 1,
        "title": "1984",
        "author": "George Orwell",
        "genre": "Dystopian Fiction"
    },
    {
        "book_id": 2,
        "title": "To Kill a Mockingbird",
        "author": "Harper Lee",
        "genre": "Classic Literature"
    },
    {
        "book_id": 3,
        "title": "The Great Gatsby",
        "author": "F. Scott Fitzgerald",
        "genre": "Historical Fiction"
    }
]}
"""

# Convert string to Python dict
response_dict = json.loads(response)
print("\n",response_dict['books'][1]["title"])

prompt = f"أنشئ قائمة بثلاثة عناوين كتب مختلقة مع مؤلفيها وأنواعها."

response = get_completion(prompt)
print(response)

prompt = f"""
مهمتك هي الإجابة بأسلوب متسق.

الطفل: علمني عن الصبر.

الجد: النهر الذي ينحت أعمق وادٍ يتدفق من نبع متواضع؛\
 أعظم سيمفونية تبدأ بنغمة واحدة؛\
 أكثر الأقمشة تعقيدًا تبدأ بخيط واحد\.

الطفل: علمني عن الصمود.
"""
response = get_completion(prompt)
print(response)

